### ISSUE TITLE
Can I put outlets in Rails template

### ISSUE THREAD

**Issue by arthurtalkgoal** [alexspeller/emblem-rails#35]
Is there any ways to put emblem outlets in my rails erb?
(instead of defining in .js.coffee?

e.g.
```
# /rails_root/app/views/layouts/application.html.erb
<div id="sidebar">
{{outlet sidebar}}  
</div>
```

allow ember handle the sidebar content.
```
# javascripts/app/templates/application.js.coffee
= render 'menu' outlet="sidebar"
```

**Comment by alexspeller** [comment]
Ember does not work like this. I'm not sure why you have a js.coffee file, emblem works with .emblem files. You should generally not have any content in your rails layout, ember renders your whole app.

In any case, this issue is not related to emblem at all. Emblem is just a shorthand for handlebars. I suggest reading the docs on the ember website to understand the basics of how ember works

**Comment by arthurtalkgoal** [comment]
oh, that's right, it's application.js.emblem
